language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - make install
script:
    - make build test
deploy:
  provider: releases
  file:
  - dist/*.whl
  - dist/*.tar.gz
  file_glob: true
  on:
    branch: develop
    tags: true
  skip_cleanup: true
  draft: true