language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - make install
script:
    - make build test
deploy:
  - provider: script
    script:
    - export REPOSITORY=pypi && make upload
    on:
      branch: develop