language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - make install
script: make

after_script:
  - echo ${TRAVIS_BRANCH}
  - if [ "$TRAVIS_BRANCH" == "develop" ]; export REPOSITORY=pypi && make upload fi
